app:
  name: "EthicsChat 4789"
  version: "0.1.0"
  default_language: "auto"
  offline_mode: false
  feedback_enabled: true
  startup_op_level: 0
  theme: "dark"
  interface_port: 8080
  auto_update_check: false
