gatekeeper:
  controller: "gatekeeper.local"
  allow_control: true
  local_only: true
  private_identity: "singularity"
  address: ""
  phone: ""
  temp_token_duration: 86400 # seconds
  authorized_temp:
    - example_phone
